---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: sovereign
  sudo: True
  gather_facts: False

  roles:
    - common
    - mailserver
    - webmail
    - blog
    - ircbouncer
    - monitoring
    - owncloud
    - vpn


